In [7]:
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load data from .npz file
data = np.load("features/symptoms.npz")
features = data["X"]
labels = data["y"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.2, random_state=42
)

# Define the parameter grid to search
param_grid = {
    "hidden_layer_sizes": [(50,), (100,), (150,)],
    "activation": ["logistic", "tanh", "relu"],
    "alpha": [0.0001, 0.001, 0.01],
    "max_iter": [200, 300, 400],
}

# Create an MLP classifier
mlp = MLPClassifier(random_state=42)

# Create the GridSearchCV object
grid_search = GridSearchCV(mlp, param_grid, cv=3, scoring="accuracy", n_jobs=-1)

# Fit the GridSearchCV object to the data
grid_search.fit(X_train, y_train)

# Get the best parameters and the corresponding model
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

# Make predictions on the test set using the best model
predictions = best_model.predict(X_test)

# Evaluate the best model
accuracy = accuracy_score(y_test, predictions)
report = classification_report(y_test, predictions)

print("Best Parameters:", best_params)
print(f"Best Model Accuracy: {accuracy}")
print("Classification Report:\n", report)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[15 15 15 ...  2 34 36]
Accuracy: 0.5497967479674797
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.68      0.81        25
           1       0.00      0.00      0.00        15
           2       0.00      0.00      0.00        26
           3       1.00      1.00      1.00        21
           4       0.38      1.00      0.55        24
           5       0.00      0.00      0.00        33
           6       0.66      1.00      0.79        19
           7       0.00      0.00      0.00        34
           8       0.00      0.00      0.00        22
           9       1.00      0.13      0.23        23
          10       1.00      1.00      1.00        23
          11       1.00      1.00      1.00        21
          12       0.23      1.00      0.37        18
          13       0.00      0.00      0.00   

C:\Users\Cristian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1) reached and the optimization hasn't converged yet.
  warnings.warn(
C:\Users\Cristian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Cristian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being se